/* modelo relacional que permita almacenar los datos de clientes que realizan compras de distintos productos que tienen un stock, 
no se puede vender un producto que no tenga un stock suficiente para satisfacer la cantidad vendida en la venta, las compras se realizan en cuenta corriente 
y los clientes pueden saldar una factura con distintos pagos, un  pago solo  afecta a  una factura, los pagos son en efectivo y solo se factura a clientes en cuenta corriente. 


CLIENTE(ID_C, NOMBRE, SALDO)
PK (ID_C)

FACTURA(NRO_F,ID_C,IMPORTE, SALDO)
PK (NRO_F)
FK (ID_C, CLIENTE)

PAGO (NRO_P, NRO_F, MONTO)
PK (NRO_P, NRO_F)
FK (NRO_F, FACTURA)

PRODUCTO(ID_P,DESCR,STOCK,PRECIO_BASE)
PK (ID_P)

DETALLE(NRO_F,ID_P,CANTIDAD,PRECIO)
PK (NRO_F, ID_P)
FK (NRO_F, FACTURA)
FK (ID_P, PRODUCTO)
*/



-- VERSION MYSQL

CREATE TABLE CLIENTE (
    ID_C INT NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    SALDO DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_C)
);

CREATE TABLE FACTURA (
    NRO_F INT NOT NULL,
    ID_C INT NOT NULL,
    IMPORTE DECIMAL(10,2) NOT NULL,
    SALDO DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_FACTURA PRIMARY KEY (NRO_F),
    CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (ID_C) REFERENCES CLIENTE(ID_C)
);

CREATE TABLE PAGO (
    NRO_P INT NOT NULL,
    NRO_F INT NOT NULL,
    MONTO DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_PAGO PRIMARY KEY (NRO_P, NRO_F),
    CONSTRAINT FK_PAGO_FACTURA FOREIGN KEY (NRO_F) REFERENCES FACTURA(NRO_F)
);

CREATE TABLE PRODUCTO (
    ID_P INT NOT NULL,
    DESCR VARCHAR(100) NOT NULL,
    STOCK INT NOT NULL,
    PRECIO_BASE DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_P),
    CONSTRAINT PRODUCTO_CHECK CHECK (STOCK >= 0)
);

CREATE TABLE DETALLE (
    NRO_F INT NOT NULL,
    ID_P INT NOT NULL,
    CANTIDAD INT NOT NULL,
    PRECIO DECIMAL(10,2) NOT NULL,
    CONSTRAINT PK_DETALLE PRIMARY KEY (NRO_F, ID_P),
    CONSTRAINT FK_DETALLE_FACTURA FOREIGN KEY (NRO_F) REFERENCES FACTURA(NRO_F),
    CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (ID_P) REFERENCES PRODUCTO(ID_P)
);


-- VERSION FIREBIRD

CREATE TABLE CLIENTE (
    ID_C INTEGER NOT NULL,
    NOMBRE VARCHAR(20) NOT NULL,
    SALDO DOUBLE PRECISION NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_C)
)

CREATE TABLE FACTURA (
    NRO_F INTEGER NOT NULL,
    ID_C INTEGER NOT NULL,
    IMPORTE DOUBLE PRECISION NOT NULL,
    SALDO DOUBLE PRECISION NOT NULL,
    CONSTRAINT PK_FACTURA PRIMARY KEY (NRO_F),
    CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (ID_C) REFERENCES CLIENTE
)

CREATE TABLE PAGO (
    NRO_P INTEGER NOT NULL,
    NRO_F INTEGER NOT NULL,
    MONTO DOUBLE PRECISION NOT NULL,
    CONSTRAINT PK_PAGO PRIMARY KEY (NRO_P, NRO_F),
    CONSTRAINT FK_PAGO_FACTURA FOREIGN KEY (NRO_F) REFERENCES FACTURA
)

CREATE TABLE PRODUCTO (
    ID_P INTEGER NOT NULL,
    DESCR VARCHAR(100) NOT NULL,
    STOCK INTEGER NOT NULL,
    PRECIO_BASE DOUBLE PRECISION NOT NULL,
    CONSTRAINT PK_PRODUCTO PRIMARY KEY (ID_P),
    CONSTRAINT PRODUCTO_CHECK CHECK (STOCK >= 0)
)

CREATE TABLE DETALLE (
    NRO_F INTEGER NOT NULL,
    ID_P INTEGER NOT NULL,
    CANTIDAD INTEGER NOT NULL,
    PRECIO DOUBLE PRECISION NOT NULL,
    CONSTRAINT PK_DETALLE PRIMARY KEY (NRO_F, ID_P),
    CONSTRAINT FK_DETALLE_FACTURA FOREIGN KEY (NRO_F) REFERENCES FACTURA,
    CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (ID_P) REFERENCES PRODUCTO
)


